#ifndef COMMONCODE_H_INCLUDED
#define COMMONCODE_H_INCLUDED

#define FTPD_CMDWRIO  0
#define FTPD_CMDRDIO  1

#define FTPD_DATAPORT 20
#define FTPD_CMDPORT 21
#define FTPD_CMDDATA_LEN 4096
#define FTPD_UNIXSOCK_LEN 1024

enum PUNIXLOGINSTATUS
{
    PUNIXSOCKLOGINOK = 1,
    PUNIXSOCKLOGINFAIL,
    PUNIXSOCKPORTOK,
    PUNIXSOCKPORTFAIL,
    PUNIXSOCKLISTOK,
    PUNIXSOCKLISTFAIL,
};

enum PUNIXCMDTYPE
{
    PUNIXSOCKLOGIN = 1,
    PUNIXSOCKPWD,
    PUNIXSOCKPORT,
    PUNIXSOCKRETR,
    PUNIXSOCKSTOR,
    PUNIXSOCKPASV,
    PUNIXSOCKSIZE,
    PUNIXSOCKCDUP,
    PUNIXSOCKDELE,
    PUNIXSOCKLIST,
    PUNIXSOCKMKD,
    PUNIXSOCKREST,


};


#endif // COMMONCODE_H_INCLUDED
