#ifndef COMMONCODE_H_INCLUDED
#define COMMONCODE_H_INCLUDED

#define FTPD_CMDWRIO  0
#define FTPD_CMDRDIO  1

#define FTPD_DATAPORT 20
#define FTPD_CMDPORT 21
#define FTPD_CMDDATA_LEN 4096
#define FTPD_UNIXSOCK_LEN 1024

enum PUNIXLOGINSTATUS
{
    PCMDRESPONDLOGINOK = 1,
    PCMDRESPONDLOGINFAIL,
    PCMDRESPONDPORTOK,
    PCMDRESPONDPORTFAIL,
    PCMDRESPONDLISTOK,
    PCMDRESPONDLISTFAIL,
    //PCMDRESPOND
};

enum PUNIXCMDTYPE
{
    PCMDREQUESTLOGIN = 1,
    PCMDREQUESTPWD,
    PCMDREQUESTPORT,
    PCMDREQUESTRETR,
    PCMDREQUESTSTOR,
    PCMDREQUESTPASV,
    PCMDREQUESTTYPE,
    PCMDREQUESTSIZE,
    PCMDREQUESTCDUP,
    PCMDREQUESTCWD,
    PCMDREQUESTDELE,
    PCMDREQUESTLIST,
    PCMDREQUESTMKD,
    PCMDREQUESTREST,
    PCMDREQUESTRMD,


};


#endif // COMMONCODE_H_INCLUDED
